name: Build Debug APK

on:
  workflow_dispatch: # این خط اجازه می‌دهد اکشن را به صورت دستی اجرا کنید
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code and Submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive' # بسیار مهم برای دریافت سورس کدهای Xray

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # نسخه استاندارد Go برای کامپایل هسته

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make Gradlew Executable
        working-directory: ./V2rayNG
        run: chmod +x ./gradlew

      - name: Build Debug APK
        working-directory: ./V2rayNG
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: v2rayNG-debug-apk
          path: V2rayNG/app/build/outputs/apk/debug/*.apk
