name: Build Debug APK

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code and Submodules
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download libv2ray AAR
        run: |
          mkdir -p ./V2rayNG/app/libs
          curl -L -o ./V2rayNG/app/libs/libv2ray.aar https://github.com/2dust/AndroidLibXrayLite/releases/latest/download/libv2ray.aar
          curl -L -o ./V2rayNG/app/libs/libv2ray-sources.jar https://github.com/2dust/AndroidLibXrayLite/releases/latest/download/libv2ray-sources.jar

      - name: Make Gradlew Executable
        working-directory: ./V2rayNG
        run: chmod +x ./gradlew

      - name: Build Debug APK (arm64-v8a only)
        working-directory: ./V2rayNG
        run: ./gradlew assembleDebug -PABI_FILTERS=arm64-v8a

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: v2rayNG-debug-apk
          path: V2rayNG/app/build/outputs/apk/**/*.apk
